
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[405] =
    {   0,
       93,   93,    0,    0,    0,    0,    0,    0,   11,   11,
      107,  105,   93,  104,   94,  105,    1,   94,   88,  105,
       95,   94,   94,   94,   95,   94,   99,   94,   94,   94,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  105,    6,    7,    6,
        8,    9,   17,   18,   11,   13,   14,   12,   93,   85,
        0,   86,    0,   91,   80,   89,   81,   90,   98,   10,
       16,   92,  103,   99,  103,  103,   82,   84,   83,  101,
      101,  101,  101,  101,  101,  101,  101,   27,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,

      101,   28,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,   87,    0,   11,   13,   12,   12,   15,  102,
      100,  103,   98,  103,  103,    0,   97,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,   25,  101,  101,  101,  101,  101,  101,
      101,  101,   20,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,    0,    0,  103,    0,   96,
       97,   97,  103,  103,   22,  101,   38,   23,  101,  101,

      101,  101,  101,   29,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,   71,
       73,   24,  101,  101,   74,   76,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,   35,
      101,  101,   19,  101,  101,  101,    0,    0,  103,    0,
       96,   96,   96,   97,  103,  103,    0,  103,   32,  101,
       34,  101,  101,  101,   36,  101,  101,  101,  101,   67,
      101,   68,   45,  101,   69,   70,   46,  101,  101,   48,
       49,  101,  101,  101,  101,  101,  101,  101,  101,  101,
       65,  101,  101,  101,  101,  101,  101,  101,  101,  101,

      101,  101,  101,   26,    0,  103,    0,  103,   96,   96,
       96,  103,    0,  103,  103,  101,  101,  101,   21,   40,
       42,   43,  101,  101,  101,  101,   64,   50,  101,   78,
       59,  101,   51,   52,   31,   53,   54,  101,  101,   66,
       37,   30,  101,   57,   77,  101,  101,  101,    0,    0,
      103,  103,  103,   96,  103,  103,  101,  101,   39,  101,
       44,   58,   47,   72,   75,   55,   60,   56,  101,   62,
      101,    0,  103,  103,  103,  103,   41,   33,   79,   61,
       63,    0,    0,  103,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    4,    0,

        2,    5,    3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       12,   13,   14,   12,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   12,   12,   19,
       20,   21,   12,    8,   22,   22,   22,   22,   23,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       12,    8,   12,    8,   22,    8,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   22,   33,   34,   35,   36,
       37,   38,   22,   39,   40,   41,   42,   43,   44,   22,
       22,   22,   12,   45,   12,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[46] =
    {   0,
        1,    2,    3,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    4,    5,    5,    6,    5,    7,    5,    5,
        5,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    5
    } ;

static yyconst flex_int16_t yy_base[417] =
    {   0,
        0,    0,   43,   44,  569,  568,  567,  566,   46,   49,
      568,  573,   52,  573,  547,    0,  573,  573,  556,    0,
      573,  545,   41,   43,  546,   47,   50,  543,  542,  541,
        0,   32,   46,   37,  526,   60,  531,   43,  516,   63,
      529,   68,   68,  520,   81,  524,  509,  573,  573,  514,
      573,  573,  573,  573,    0,   83,  573,   98,   91,  573,
      546,  573,  540,  573,  573,  573,  573,  573,  104,  573,
      573,  573,  532,  107,    0,   99,  573,  573,  573,    0,
      512,  520,  507,  522,  517,  508,  514,  500,  501,  506,
      505,  499,   90,  509,   37,   87,  508,  105,  507,  495,

      492,    0,  491,  497,  491,  497,  487,  101,  503,  485,
      486,  498,  484,  490,  483,  478,  489,  480,  485,  477,
      477,  482,  573,  489,    0,  136,  126,  131,  573,  506,
      573,  493,  131,  137,    0,  492,  140,  475,  484,  479,
      467,  481,  120,  480,  478,  474,  461,  463,  460,  456,
      458,  455,  467,    0,  462,  452,  129,  468,  463,  456,
      457,  124,    0,  454,  448,  450,  131,  448,  460,  441,
      450,  445,   91,  448,  455,  436,  436,  133,  448,  447,
      435,  446,  440,  432,  436,  439,  149,  160,  450,  163,
      164,  167,    0,  179,    0,  434,    0,    0,  427,  424,

      432,  421,  428,    0,  433,  420,  422,  418,  425,  158,
      420,  419,  162,  427,  415,  416,  418,  416,  408,  417,
        0,    0,  410,  405,  414,    0,  401,  408,  403,  405,
      411,  397,  413,  401,  400,  409,  408,  401,  408,    0,
      390,  398,    0,  393,  396,  399,  391,  183,  189,  407,
      192,  196,  200,  209,  215,  220,  406,  405,    0,  394,
        0,  385,  386,  391,    0,  390,  378,  385,  379,    0,
      377,    0,    0,  372,    0,    0,    0,  384,  382,    0,
        0,  382,  385,  369,  378,  382,  377,  376,  367,  375,
        0,  372,  358,  358,  369,  356,  365,  361,  353,  356,

      345,  339,  302,    0,  313,  225,  318,  226,  229,  230,
      243,  249,  314,  252,  310,  285,  278,  275,    0,    0,
        0,    0,  274,  271,  278,  267,    0,    0,  260,    0,
        0,  259,    0,    0,    0,    0,    0,  265,  261,    0,
        0,    0,  258,    0,    0,  241,  252,  236,  269,  251,
      256,  260,  269,  273,  277,  286,  226,  232,    0,  227,
        0,    0,    0,    0,    0,    0,    0,    0,  222,    0,
      221,  181,  290,  294,  303,  307,    0,    0,    0,    0,
        0,  204,  199,  311,  189,  193,  178,  185,  183,  169,
      172,  185,  172,  136,  133,  226,  304,  117,  573,  112,

      573,  573,  573,  573,  340,  347,  354,  361,  365,  369,
      371,   85,  378,  385,   50,  387
    } ;

static yyconst flex_int16_t yy_def[417] =
    {   0,
      404,    1,  405,  405,  406,  406,  407,  407,  408,  408,
      404,  404,  404,  404,  404,  409,  404,  404,  404,  410,
      404,  404,  404,  404,  404,  404,  411,  404,  404,  404,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  404,  404,  404,  404,
      404,  404,  404,  404,  413,  404,  404,  414,  404,  404,
      409,  404,  404,  404,  404,  404,  404,  404,  411,  404,
      404,  404,  404,  411,  415,  415,  404,  404,  404,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  404,  404,  413,  404,  414,  414,  404,  409,
      404,  404,  411,  415,  415,  404,  416,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  404,  411,  415,  404,  416,
      411,  416,  415,  415,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  404,  411,  415,  404,
      416,  411,  416,  411,  415,  415,  404,  415,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  404,  415,  404,  416,  411,  416,
      411,  415,  404,  416,  404,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  404,  404,
      416,  411,  416,  411,  411,  416,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  404,  411,  416,  411,  411,  412,  412,  412,  412,
      412,  404,  404,  411,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,

      404,  404,  404,    0,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404
    } ;

static yyconst flex_int16_t yy_nxt[619] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   12,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   31,   31,   32,   33,   34,   35,   36,   37,
       31,   38,   31,   31,   31,   39,   31,   40,   41,   42,
       43,   44,   45,   46,   47,   49,   49,   56,   57,   56,
       56,   57,   56,   59,   65,   59,  135,   67,   58,   70,
       66,   58,   68,   71,   87,   73,   72,   74,   81,   83,
       82,  102,   76,   88,  153,  154,   84,   76,  103,   85,
       50,   50,   86,   90,  126,   91,  126,   92,   93,   94,
      105,   80,   59,  109,   59,  110,   95,   96,   97,   98,

       99,  106,  115,  100,  107,  111,  116,  112,  113,  118,
      128,  114,  136,  136,  129,  232,  137,  119,  120,  132,
      121,  133,   73,  150,   74,  155,  134,  151,  156,   76,
      158,  134,  159,  233,   76,  168,  169,  126,  404,  126,
      403,  170,  404,  128,  171,  402,  132,  129,  133,  220,
      189,  189,  214,  188,  190,  132,  225,  192,  188,  200,
      201,  238,  194,  221,  132,  215,  248,  194,  239,  397,
      226,  249,  396,  250,  250,  395,  249,  251,  132,  132,
      253,  254,  132,  270,  192,  194,  255,  275,  394,  256,
      194,  255,  257,  257,  256,  271,  258,  272,  132,  393,

      248,  276,  307,  307,  392,  306,  308,  132,  391,  310,
      306,  132,  390,  311,  194,  132,  389,  253,  255,  194,
      382,  383,  256,  255,  132,  388,  254,  256,  257,  257,
      387,  312,  258,  313,  313,  386,  312,  314,  350,  350,
      385,  132,  351,  353,  132,  132,  354,  310,  194,  381,
      380,  255,  256,  194,  398,  379,  255,  256,  132,  378,
      311,  399,  313,  313,  377,  312,  314,  132,  373,  356,
      312,  132,  372,  374,  194,  132,  371,  375,  194,  194,
      370,  369,  255,  194,  132,  368,  353,  255,  132,  367,
      354,  256,  132,  366,  376,  312,  256,  365,  364,  255,

      312,  132,  363,  356,  255,  132,  362,  384,  256,  132,
      361,  374,  255,  256,  360,  359,  256,  255,  132,  358,
      375,  256,  132,  357,  376,  312,  132,  315,  384,  312,
      312,  355,  400,  312,  312,  352,  349,  348,  312,  401,
       48,   48,   48,   48,   48,   48,   48,   51,   51,   51,
       51,   51,   51,   51,   53,   53,   53,   53,   53,   53,
       53,   55,   55,   55,   55,   55,   55,   55,   61,   61,
       61,   61,   63,   63,   63,   63,   75,   75,  125,  347,
      346,  345,  125,  125,  125,  127,  127,  344,  127,  127,
      127,  127,  193,  193,  343,  342,  341,  340,  339,  338,

      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  258,  315,  309,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  274,  273,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  252,  247,  246,
      245,  244,  243,  242,  241,  240,  237,  236,  235,  234,
      231,  230,  229,  228,  227,  224,  223,  222,  219,  218,
      217,  216,  213,  212,  211,  210,  209,  208,  207,  206,

      205,  204,  203,  202,  199,  198,  197,  196,  195,  191,
      187,  130,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  167,  166,  165,
      164,  163,  162,  161,  160,  157,  152,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  139,  138,   69,
      131,  130,  124,  123,  122,  117,  108,  104,  101,   89,
       79,   78,   77,   69,   64,   62,   60,  404,   54,   54,
       52,   52,   11,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,

      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404
    } ;

static yyconst flex_int16_t yy_chk[619] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    9,    9,    9,
       10,   10,   10,   13,   23,   13,  415,   24,    9,   26,
       23,   10,   24,   26,   34,   27,   26,   27,   32,   33,
       32,   38,   27,   34,   95,   95,   33,   27,   38,   33,
        3,    4,   33,   36,   56,   36,   56,   36,   36,   36,
       40,  412,   59,   42,   59,   42,   36,   36,   36,   36,

       36,   40,   43,   36,   40,   42,   43,   42,   42,   45,
       58,   42,   76,   76,   58,  173,   76,   45,   45,   69,
       45,   69,   74,   93,   74,   96,   69,   93,   96,   74,
       98,   69,   98,  173,   74,  108,  108,  126,  127,  126,
      400,  108,  127,  128,  108,  398,  133,  128,  133,  162,
      134,  134,  157,  133,  134,  137,  167,  137,  133,  143,
      143,  178,  137,  162,  187,  157,  187,  137,  178,  395,
      167,  187,  394,  188,  188,  393,  187,  188,  190,  191,
      190,  191,  192,  210,  192,  190,  191,  213,  392,  192,
      190,  191,  194,  194,  192,  210,  194,  210,  248,  391,

      248,  213,  249,  249,  390,  248,  249,  251,  389,  251,
      248,  252,  388,  252,  251,  253,  387,  253,  252,  251,
      372,  372,  253,  252,  254,  386,  254,  253,  255,  255,
      385,  254,  255,  256,  256,  383,  254,  256,  306,  306,
      382,  308,  306,  308,  309,  310,  309,  310,  308,  371,
      369,  309,  310,  308,  396,  360,  309,  310,  311,  358,
      311,  396,  312,  312,  357,  311,  312,  314,  350,  314,
      311,  351,  349,  351,  314,  352,  348,  352,  351,  314,
      347,  346,  352,  351,  353,  343,  353,  352,  354,  339,
      354,  353,  355,  338,  355,  354,  353,  332,  329,  355,

      354,  356,  326,  356,  355,  373,  325,  373,  356,  374,
      324,  374,  373,  356,  323,  318,  374,  373,  375,  317,
      375,  374,  376,  316,  376,  375,  384,  315,  384,  376,
      375,  313,  397,  384,  376,  307,  305,  303,  384,  397,
      405,  405,  405,  405,  405,  405,  405,  406,  406,  406,
      406,  406,  406,  406,  407,  407,  407,  407,  407,  407,
      407,  408,  408,  408,  408,  408,  408,  408,  409,  409,
      409,  409,  410,  410,  410,  410,  411,  411,  413,  302,
      301,  300,  413,  413,  413,  414,  414,  299,  414,  414,
      414,  414,  416,  416,  298,  297,  296,  295,  294,  293,

      292,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      279,  278,  274,  271,  269,  268,  267,  266,  264,  263,
      262,  260,  258,  257,  250,  247,  246,  245,  244,  242,
      241,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  225,  224,  223,  220,  219,  218,
      217,  216,  215,  214,  212,  211,  209,  208,  207,  206,
      205,  203,  202,  201,  200,  199,  196,  189,  186,  185,
      184,  183,  182,  181,  180,  179,  177,  176,  175,  174,
      172,  171,  170,  169,  168,  166,  165,  164,  161,  160,
      159,  158,  156,  155,  153,  152,  151,  150,  149,  148,

      147,  146,  145,  144,  142,  141,  140,  139,  138,  136,
      132,  130,  124,  122,  121,  120,  119,  118,  117,  116,
      115,  114,  113,  112,  111,  110,  109,  107,  106,  105,
      104,  103,  101,  100,   99,   97,   94,   92,   91,   90,
       89,   88,   87,   86,   85,   84,   83,   82,   81,   73,
       63,   61,   50,   47,   46,   44,   41,   39,   37,   35,
       30,   29,   28,   25,   22,   19,   15,   11,    8,    7,
        6,    5,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,

      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
#include "y.tab.h"
#include <stdio.h>

int	printTokenOn=1;
int	printSourceOn=1;
int 	lineCount=0;
int	wordCount=0;
int 	numStrings = 5;
char	**lineContents = NULL; 
FILE*	f;

void addWordToLine();
void endOfLine();
void comment();
int yywrap();
void lexerError();
void freeLineContents();


#line 750 "lex.yy.c"

#define INITIAL 0
#define PRAGMA 1
#define ERROR 2
#define SINGLECOMMENT 3
#define MULTICOMMENT 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 42 "scanner.l"


#line 944 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 405 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 573 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "scanner.l"
{addWordToLine(); BEGIN(PRAGMA);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 45 "scanner.l"
{printSourceOn=1; addWordToLine();}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 46 "scanner.l"
{printSourceOn=0; addWordToLine();} 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "scanner.l"
{printTokenOn=1; addWordToLine();} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "scanner.l"
{printTokenOn=0; addWordToLine();}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 "scanner.l"
{freeLineContents();
  				lineContents = (char**)malloc(sizeof(char*)*numStrings); 
 				addWordToLine();
				 BEGIN(ERROR);}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 53 "scanner.l"
{endOfLine(); BEGIN(INITIAL);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "scanner.l"
{addWordToLine();}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 56 "scanner.l"
{lexerError(); BEGIN(INITIAL);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "scanner.l"
{addWordToLine(); BEGIN(MULTICOMMENT);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "scanner.l"
{addWordToLine();} /* eat anythong that's not a '*' */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "scanner.l"
{addWordToLine();} /* eat '*' not followed by '/' */
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "scanner.l"
{addWordToLine();}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 63 "scanner.l"
{endOfLine();}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 64 "scanner.l"
{addWordToLine(); BEGIN(INITIAL);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "scanner.l"
{addWordToLine(); BEGIN(SINGLECOMMENT);}  
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "scanner.l"
{addWordToLine(); }	
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 68 "scanner.l"
{endOfLine();BEGIN(INITIAL);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return VOID;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return INT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return DOUBLE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return BOOL;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return CHAR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return K_NULL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FOR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return WHILE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return DO;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return IF;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return ELSE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return SWITCH;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return RETURN;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return BREAK;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return CONTINUE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 85 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return CONST;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 86 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return TRUE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 87 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FALSE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 88 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return STRUCT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return CASE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 90 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return DEFAULT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 92 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FCLOSE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 93 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return CLEARERR;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 94 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FERROR;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 95 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FFLUSH;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 96 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FGETPOS;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FOPEN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 98 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FREAD;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FREOPEN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FSEEK;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FTELL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FWRITE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return REMOVE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 104 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return RENAME;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 105 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return REWIND;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return SETBUF;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 107 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return SETVBUF;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 108 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return TMPFILE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 109 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return TMPNAM;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 110 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FPRINTF;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 111 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return PRINTF;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 112 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return SPRINTF;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return VFPRINTF;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return VPRINTF;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return VSPRINTF;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FSCANF;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 117 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return SCANF;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 118 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return SSCANF;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 119 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FGETC;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 120 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FGETS;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 121 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FPUTC;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 122 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FPUTS;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 123 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return GETC;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 124 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return GETCHAR;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 125 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return GETS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 126 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return PUTC;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 127 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return PUTCHAR;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 128 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return PUTS;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 129 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return UNGETC;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 130 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return PERROR;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 131 "scanner.l"
{if(printTokenOn==1) printf("#key:%s\n",yytext);  addWordToLine(); return FFPRINTF;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 133 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return INC_OP;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 134 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return DEC_OP;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 135 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return LE_OP;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 136 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return GE_OP;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 137 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return EQ_OP;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 138 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return NE_OP;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 139 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return AND_OP;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return OR_OP;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 141 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return POINTER_OP;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 143 "scanner.l"
{if(printTokenOn==1) printf("#assign:%s\n",yytext);  addWordToLine(); return ADD_ASSIGN;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 144 "scanner.l"
{if(printTokenOn==1) printf("#assign:%s\n",yytext);  addWordToLine(); return SUB_ASSIGN;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 145 "scanner.l"
{if(printTokenOn==1) printf("#assign:%s\n",yytext);  addWordToLine(); return MUL_ASSIGN;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 146 "scanner.l"
{if(printTokenOn==1) printf("#assign:%s\n",yytext);  addWordToLine(); return DIV_ASSIGN;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 148 "scanner.l"
{addWordToLine();}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 149 "scanner.l"
{if(printTokenOn==1) printf("#op:%s\n",yytext);  addWordToLine(); return *yytext;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 150 "scanner.l"
{if(printTokenOn==1) printf("#punc:%s\n",yytext);  addWordToLine(); return *yytext;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 151 "scanner.l"
{if(printTokenOn==1) printf("#sci:%s\n",yytext);  addWordToLine(); return NUMBER_SCI;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 152 "scanner.l"
{if(printTokenOn==1) printf("#sci:%s\n",yytext);  addWordToLine(); return NUMBER_SCI;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 153 "scanner.l"
{if(printTokenOn==1) printf("#double:%s\n",yytext);  addWordToLine(); return NUMBER_DOUBLE;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 154 "scanner.l"
{if(printTokenOn==1) printf("#integer:%s\n",yytext);  addWordToLine(); return NUMBER_INTEGER;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 155 "scanner.l"
{if(printTokenOn==1) printf("#char:%s\n",yytext);  addWordToLine(); return CHARACTER;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 156 "scanner.l"
{if(printTokenOn==1) printf("#id:%s\n",yytext);  addWordToLine(); return IDENTIFIER;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 157 "scanner.l"
{char *stringtext= (char*)malloc(sizeof(char)*(yyleng-1));
			strncpy(stringtext,&yytext[1],yyleng-2);
			strncpy(&stringtext[yyleng-2],&yytext[yyleng],1);
			printf("#string:%s\n",stringtext);
			addWordToLine();
			free(stringtext);
			return STRING;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 164 "scanner.l"
{freeLineContents();
  			lineContents = (char**)malloc(sizeof(char*)*numStrings); 
 			addWordToLine();
			BEGIN(ERROR);
			return INVALIDNUM;}
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 169 "scanner.l"
{endOfLine();}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 170 "scanner.l"
{freeLineContents();
  			lineContents = (char**)malloc(sizeof(char*)*numStrings); 
 			addWordToLine();
			BEGIN(ERROR);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 176 "scanner.l"
ECHO;
	YY_BREAK
#line 1578 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PRAGMA):
case YY_STATE_EOF(ERROR):
case YY_STATE_EOF(SINGLECOMMENT):
case YY_STATE_EOF(MULTICOMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 405 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 405 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 404);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "scanner.l"



/*-----------------------
addWordToLine() Adds word to line, dynamically allocates more space if 
needed
------------------------*/
void addWordToLine(){
	if (wordCount>=numStrings-1){
		numStrings*=2;
		lineContents=realloc(lineContents,numStrings*sizeof(lineContents));
	}
	lineContents[wordCount] = (char*) malloc(sizeof(char) * yyleng + 1);
	strcpy(lineContents[wordCount],yytext);
	wordCount++;
}

/*-----------------------
endOfLine() Flushes a synctactically correct line to the file
------------------------*/
void endOfLine(){
	//print line
	lineCount++;

	if(printSourceOn==1){
		printf("%d:", lineCount);
		int j;
		for(j=0;j<wordCount;j++)
			printf("%s",lineContents[j]);
		printf("\n");
	}

	//free and reallocate, reset vars
	freeLineContents();
	lineContents = (char**) malloc(sizeof(char*) * numStrings);
}


int yywrap(){
	return 1; /*eof*/
}

/*-----------------------
lexerError() Prints error to stderr  
------------------------*/
void lexerError(char *message){
	fprintf(stderr, "Error at line %d: ",lineCount+1);
	int j;
	for(j=0;j<wordCount;j++)
		fprintf(stderr,"%s",lineContents[j]);
	fprintf(stderr,"\n");
	//free and reallocate, reset vars
	freeLineContents();
	exit(1);
}

/*-----------------------
addWordToLine() Clean up dynamically allocated array lineContents() 
------------------------*/
void freeLineContents(){

	int i;
	for(i=0;i<wordCount;i++)
		free(lineContents[i]);
	free(lineContents);
	numStrings=5;
	wordCount=0;
}

void yyerror(const char *msg ) {	
	fprintf( stderr, "*** Error at line %d: ", lineCount+1);
	int j;
	for(j=0;j<wordCount;j++)
		fprintf(stderr,"%s",lineContents[j]);
	fprintf(stderr,"\n");
	fprintf( stderr, "\n" );
	fprintf( stderr, "Unmatched token: %s\n", yytext );
	fprintf( stderr, "*** syntax error\n");	
	freeLineContents();
	exit(-1);
}

